### PR TITLE
Auto generate api.md using mocha

### PR DESCRIPTION
**Pull request by dignifiedquire**
Replaces #105

### CODE REVIEW

**Comment by diasdavid** [comment]
ready to merge. It is not the most beautiful documentation ever, but certainly has more information than what we have now. Any thoughts? Merge and release?

**Comment by diasdavid** [comment]
I was going to do a clean up but then I noticed this slices the function calls off :(

image

**Comment by Dignifiedquire** [comment]
@diasdavid now this sucks. Would you mind filing a bug at https://github.com/mochajs/mocha/issues?

**Comment by diasdavid** [comment]
done on https://github.com/mochajs/mocha/issues/1978

**Comment by diasdavid** [comment]
closing this one in favor of https://github.com/ipfs/js-ipfs-api/pull/228

**Pull request closed without merging**
