### PR TITLE
attempt to handle changes to ipfs swarm peers api

### PR DESCRIPTION
**Pull request by whyrusleeping**
so obviously i don't javascript, but these tests failing my CI is getting old so i've made an effort.

Can someone who knows what they are doing help out here?

cc @diasdavid @dignifiedquire @VictorBjelkholm

### CODE REVIEW

**Comment by dignifiedquire** [comment]
thanks @whyrusleeping will take a look later today

**Comment by dignifiedquire** [comment]
Ready for review and merge

**Comment by dignifiedquire** [comment]
Additional tests are in https://github.com/ipfs/interface-ipfs-core/pull/94

**Comment by diasdavid** [comment]
thank you @dignifiedquire 

So, since we need to provide the same api for js-ipfs and js-ipfs-api and having two return types is weird, the best is just to level up js-ipfs to the latest go-ipfs swarm peers API and make js-ipfs-api always return the same thing, of course that with the caveat that when contacting a go-ipfs 0.4.4 node, some of the properties will be undefined.

**Comment by dignifiedquire** [comment]
@diasdavid updated both PRs.

**Comment by diasdavid** [comment]
👍 now just needs an update on js-ipfs ipfs.swarm.peers

**Comment by dignifiedquire** [comment]
@diasdavid js-ipfs PR https://github.com/ipfs/js-ipfs/pull/600

**Comment by dignifiedquire** [comment]
> Tests pass locally, everything LG

@diasdavid can we ship this?

**Comment by haadcode** [comment]
Ship it! :)

**Pull request merged**
