### PR TITLE
browser-add-file

### PR DESCRIPTION
**Pull request by nycoliver**
Example showing broken file add in browser. See https://github.com/ipfs/js-ipfs-api/issues/344#issuecomment-243900156 and https://github.com/ipfs/js-ipfs-api/pull/335 for context.

### CODE REVIEW

**Comment by nycoliver** [comment]
Tests failing because FileReader is undefined in node environment. Not sure how to fix...

**Comment by nginnever** [comment]
Thanks for posting this @nycoliver 

>Tests failing because FileReader is undefined in node environment. Not sure how to fix...

That's just a linting error, so really just lint doesn't know about FileReader global since node never runs that example code. You could just instantiate a FileSwarm contract at the scope you need with some like ``let FileReader``

This example should be

**Comment by diasdavid** [comment]
@nycoliver please add `/* globals FileReader */`at the top and squash the commits for the merge :)

**Comment by diasdavid** [comment]
@nycoliver looks all good now. Can you coalesce the commits?

```
git rebase -i HEAD~6
# squash them all
# reword the commit message to `feat(examples): add browser-add example` 
```

**Comment by nycoliver** [comment]
First pull request, almost got it...

**Comment by diasdavid** [comment]
Here is a good tutorial http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html let me know if you run into trouble, I'm available on IRC as daviddias on the #IPFS channel in freenode

**Comment by diasdavid** [comment]
Congrats on your first pull request 🎉🎉🎉🎉👏👏👏👏👏👏👏👏👏

**Pull request merged**
