### PR TITLE
go-ipfs 0.4.14 compat

### PR DESCRIPTION
**Pull request by VictorBjelkholm**
Created to support work on https://github.com/ipfs/go-ipfs/issues/4818#issuecomment-373686215

Since 0.4.14, go-ipfs now returns an empty array rather than null.

This should be considered a breaking change for consumers of this
library.

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
Update: made sure it passes with 0.4.14-rc3-d475318ff, no issues currently

**Comment by VictorBjelkholm** [comment]
Update: tried with latest go-ipfs master (`0.4.14-rc2-4bdbe1a99` at the time of writing this) and everything still passes :+1:

**Comment by VictorBjelkholm** [comment]
@diasdavid could you do the release dance to get go-ipfs-dep and js-ipfsd-ctl released with new go-ipfs version? 0.4.14 has been released now

**Comment by diasdavid** [comment]
image

But I'll wait for CI ;)

**Comment by diasdavid** [comment]
image

**Pull request merged**
