### PR TITLE
feat: add support to non-scheme urls

### LINKED ISSUE #139: constructor should take non-scheme specific urls
this should work:

``` js
var ipfs = ipfsAPI("//localhost:5001")
```

### PR DESCRIPTION
**Pull request by hacdias**
Closes #139.

### CODE REVIEW

**Comment by hacdias** [comment]
Pinging @diasdavid

**Comment by hacdias** [comment]
Ping @diasdavid

**Comment by lgierth** [comment]
Ugh I don't know whether it's a good to support URLs here. Is there precedent of other IPFS areas supporting URLs?

**Comment by diasdavid** [comment]
@lgierth not anywhere, no. Given that this was a @jbenet request from 2015, I'll defer to him to follow up and tell us if it still is important.

**Comment by hacdias** [comment]
Rebased.

**Comment by hacdias** [comment]
Half travis is passing. I'm not sure what I should do to make it all pass.

**Comment by lgierth** [comment]
Let's not accept URLs

**Comment by hacdias** [comment]
Can I close this then?

**Comment by diasdavid** [comment]
@lgierth fine then.

**Pull request closed without merging**
