### PR TITLE
[WIP] Jenkins integration

### PR DESCRIPTION
**Pull request by VictorBjelkholm**

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
@diasdavid If this looks fine to you, could you merge it?

**Comment by diasdavid** [comment]
@VictorBjelkholm is this PR mergeable? I'm still not super sure of the state of CI, if there are things to be merged, please tag reviewers and note that on the PRs, if things are WIP, then write that down too.

**Comment by diasdavid** [comment]
Also, please follow commit guidelines. Thank you.

**Comment by VictorBjelkholm** [comment]
@diasdavid thanks. Fixed the commit msg to be correct according to our guidelines. Due to current issue with Jenkins, builds are currently failing and I'll update this PR once it's mergable.

Ref: https://github.com/ipfs/jenkins/issues/59

**Comment by diasdavid** [comment]
@VictorBjelkholm understood, thank you for clarifying :)

**Comment by VictorBjelkholm** [comment]
@diasdavid the issue mentioned above have now been fixed and this is ready to be merged :)

**Comment by VictorBjelkholm** [comment]
Closing this as nothing will be required to change in the repository to activate CI.

**Pull request closed without merging**
