### PR TITLE
feat: Add promise based api

### LINKED ISSUE #80: Promisses API
Most environments now support the more pleasant API of `Promise` ( https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Promise ), that is easier to handle and chain together. We should think about migrating to start using promises instead of callbacks where applicable.

List of browsers that supports it current: https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Promise
(IE doesn't support it + some olders versions of other browsers, probably have to provide an existing shim as well...)

In node, promises have been natively supported since 0.12 so shouldn't be an issue there.

### PR DESCRIPTION
**Pull request by dignifiedquire**
All methods return a promise when not passed a callback

Closes #80

### CODE REVIEW

**Comment by diasdavid** [comment]
After the past discussions about having a promises implementations and the implications that would bring, this seems by far the most elegant solution (as it is almost minimal and only touches the code partially and gives the desired feature).

Before merging, I would like everyone that chimed in on the promises API discussion to give their review (if possible). The discussion happened here https://github.com/ipfs/js-ipfs-api/issues/80 and the people involved are: @VictorBjelkholm, @RichardLitt, @harlantwood, @travisperson and @bcomnes

**Comment by harlantwood** [comment]
+100

**Comment by fazo96** [comment]
I really hope this gets merged!

**Comment by RichardLitt** [comment]
LGTM!

**Comment by diasdavid** [comment]
It is time.. :)

**Comment by dignifiedquire** [comment]
whoo

**Comment by RichardLitt** [comment]
@jbenet You mentioned that you would like to discuss this. Here is the relevant PR for that discussion.

**Pull request merged**
