### PR TITLE
Updating CI files

### PR DESCRIPTION
**Pull request by VictorBjelkholm**
This commit updates all CI scripts to the latest version

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
Some windows tests are failing and timing out. Unsure of why right now.

**Comment by VictorBjelkholm** [comment]
6 failing tests.

```
  1) .pubsub

       multiple nodes connected

         multiple nodes

           receive multiple messages:

     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  


  2) .pubsub

       multiple nodes connected

         load tests

           send/receive 10k messages:

     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  


  3) .pubsub

       multiple nodes connected

         load tests

           call subscribe/unsubscribe 1k times:


      Uncaught AssertionError: expected [ Array(2) ] to deeply equal []

      + expected - actual


      -[

      -  "pubsub-tests-b1e5b8d290653d7dad64ae20d5b65f34"

      -  "pubsub-tests-a3612b1f78224b70f099bf5bcf0cd718"

      -]

      +[]

      

      at ipfs1.pubsub.ls (node_modules\interface-ipfs-core\src\pubsub.js:648:35)

      at stringlistToArray (src\utils\stringlist-to-array.js:6:3)

      at send (src\utils\send-request.js:207:7)

      at f (node_modules\once\once.js:25:25)

      at streamToValue (src\utils\stream-to-json-value.js:30:5)

      at concat (src\utils\stream-to-value.js:12:22)

      at ConcatStream.<anonymous> (node_modules\concat-stream\index.js:36:43)

      at finishMaybe (node_modules\readable-stream\lib\_stream_writable.js:607:14)

      at endWritable (node_modules\readable-stream\lib\_stream_writable.js:615:3)

      at ConcatStream.Writable.end (node_modules\readable-stream\lib\_stream_writable.js:571:41)

      at IncomingMessage.onend (_stream_readable.js:598:10)

      at endReadableNT (_stream_readable.js:1054:12)

      at _combinedTickCallback (internal/process/next_tick.js:138:11)

      at process._tickCallback (internal/process/next_tick.js:180:9)


  4) .refs

       "before all" hook:


      Uncaught AssertionError: expected 'Qma8UM1iXpRjXJaG9PKxWzz9bnpruASGpLDKEy5cd5Apmz' to deeply equal 'QmQao3KNcpCsdXaLGpjieFGMfXzsSXgsf6Rnc5dJJA3QMh'

      + expected - actual


      -Qma8UM1iXpRjXJaG9PKxWzz9bnpruASGpLDKEy5cd5Apmz

      +QmQao3KNcpCsdXaLGpjieFGMfXzsSXgsf6Rnc5dJJA3QMh

      

      at waterfall (test\refs.spec.js:33:30)

      at nextTask (node_modules\async\waterfall.js:16:14)

      at next (node_modules\async\waterfall.js:23:9)

      at node_modules\async\internal\onlyOnce.js:12:16

      at f (node_modules\once\once.js:25:25)

      at ConcatStream (src\utils\send-one-file-multiple-results.js:12:46)

      at ConcatStream.<anonymous> (node_modules\concat-stream\index.js:36:43)

      at finishMaybe (node_modules\readable-stream\lib\_stream_writable.js:607:14)

      at endWritable (node_modules\readable-stream\lib\_stream_writable.js:615:3)

      at ConcatStream.Writable.end (node_modules\readable-stream\lib\_stream_writable.js:571:41)

      at Duplex.onend (_stream_readable.js:598:10)

      at endReadableNT (_stream_readable.js:1054:12)

      at _combinedTickCallback (internal/process/next_tick.js:138:11)

      at process._tickCallback (internal/process/next_tick.js:180:9)


  5) 'deal with HTTP weirdness' tests

       does not crash if no content-type header is provided:

     Uncaught AssertionError: expected [Error: read ECONNRESET] to not exist

      at ipfsAPI.config.replace (test\request-api.spec.js:28:28)

      at Duplex.sendFile (src\utils\send-one-file.js:10:16)

      at Duplex.f (node_modules\once\once.js:25:25)

      at send (src\utils\send-files-stream.js:114:26)

      at f (node_modules\once\once.js:25:25)

      at ClientRequest.req.on (src\utils\send-request.js:167:5)

      at Socket.socketErrorListener (_http_client.js:389:9)

      at emitErrorNT (internal/streams/destroy.js:64:8)

      at _combinedTickCallback (internal/process/next_tick.js:138:11)

      at process._tickCallback (internal/process/next_tick.js:180:9)


  6) .util

       .fsAdd should add

         a directory with an odd name:

     Uncaught AssertionError: expected [Error: expected at least one child dir, got none] to not exist

      at Duplex.ipfs.util.addFromFs (test\util.spec.js:58:28)

      at Duplex.f (node_modules\once\once.js:25:25)

      at DestroyableTransform.response.on (src\utils\send-files-stream.js:128:47)

      at IncomingMessage.res.on (src\utils\send-request.js:59:24)

      at endReadableNT (_stream_readable.js:1054:12)

      at _combinedTickCallback (internal/process/next_tick.js:138:11)

      at process._tickCallback (internal/process/next_tick.js:180:9)




Command failed: mocha --timeout 5000 --ui bdd --colors --exit test\node.js test\**\*.spec.js
```

**Comment by diasdavid** [comment]
@richardschneider could you check the Windows issues, please? thanks!

**Comment by richardschneider** [comment]
`.util.fsAdd should add.a directory with an odd name` is failing because the `[` is treated as a [special magic character](https://www.npmjs.com/package/glob#glob-primer) in `glob`..

**Pull request closed without merging**
