### PR TITLE
Implement all of the swarm API calls

### LINKED ISSUE #252: Implement all of the swarm API calls
https://github.com/ipfs/js-ipfs-api/blob/master/src/api/swarm.js#L7-L8

`swarm` is still missing:

- disconnect
- addrs
- addrs local

This is needed for `js-ipfs`

### PR DESCRIPTION
**Pull request by xicombd**
Closes #252

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Cool. But please wait with merging until aegir is merged as this will result in some annoying merge conflicts otherwise

**Comment by xicombd** [comment]
Fine by me 👍

**Comment by dignifiedquire** [comment]
@xicombd merged, can you rebase please?

**Comment by xicombd** [comment]
@dignifiedquire done! 🚀

**Comment by dignifiedquire** [comment]
LGTM

**Comment by diasdavid** [comment]
Awesome!! :D Thank you @xicombd :D

**Pull request merged**
