### PR TITLE
test: split tests into multiple files

### PR DESCRIPTION
**Pull request by Dignifiedquire**
browser tests are not yet passing, too many inter test dependencies :(

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Fixed :) should be all good now

**Comment by Dignifiedquire** [comment]
@diasdavid please take a look :smile:

**Comment by diasdavid** [comment]
This is sweet! I love having all the things organized, great work :) 

Running the tests, I'm getting:

```
FAILED TESTS:
  .log
    ✖ .log.tail
      Chrome 46.0.2490 (Mac OS X 10.11.2)
    Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.

```

On Node tests, it passes:

```
.log
    ✓ .log.tail (8863ms)
```

Does it pass in your machine? Travis also shows other bugs

**Comment by Dignifiedquire** [comment]
Yes all passing locally, might need to increase some timeouts, ipfs is quite slow at times especially around `log/tail` 

```
gulp
[13:57:24] Using gulpfile ~/opensource/ipfs/node-ipfs-api/gulpfile.js
[13:57:24] Starting 'default'...
[13:57:24] Starting 'lint'...
[13:57:27] Finished 'lint' after 3.56 s
[13:57:27] Starting 'test'...
[13:57:27] Starting 'test:node'...
[13:57:27] Starting 'daemons:start'...
  ipfs init done - (bootstrap and mdns off) - b
  ipfs init done - (bootstrap and mdns off) - c
  ipfs init done - (bootstrap and mdns off) - a
[13:57:32] Finished 'daemons:start' after 4.37 s
[13:57:32] Starting 'mocha'...


  ipfsAPI constructor tests
    parameter permuations
      ✓ opts
      ✓ mutliaddr, opts
      ✓ host, port
      ✓ host, port, opts

  nodes
    ✓ connect Node a to b and c (54ms)

  .add
    ✓ add file
    ✓ add buffer
    ✓ add BIG buffer (682ms)
    ✓ add path (66ms)
    ✓ add a nested dir (86ms)
    ✓ add stream
    ✓ add url (414ms)

  .block
    ✓ block.put
    ✓ block.get

  .cat
    ✓ cat
    ✓ cat BIG file (352ms)

  .commands
    ✓ lists commands

  .config
    ✓ .config.{set, get}
    ✓ .config.show
    ✓ .config.replace

  .dht
    ✓ returns an error when getting a non-existent key from the DHT
    ✓ puts and gets a key value pair in the DHT
    ✓ .dht.findprovs

  .diag
    ✓ .diag.net
    ✓ .diag.sys (53ms)

  .id
    ✓ id

  API
    ✓ has the api object

  .log
    ✓ .log.tail (272ms)

  .name
    ✓ .name.publish
    ✓ .name.resolve

  .object
    ✓ object.put
    ✓ object.get
    ✓ object.data
    ✓ object.stat
    ✓ object.links
    ✓ object.patch

  .pin
    ✓ .pin.add
    ✓ .pin.list
    ✓ .pin.remove

  .ping
    ✓ ping another peer (1023ms)

  .refs
    ✓ refs

  .send
    - used by every command

  .swarm
    ✓ .swarm.peers
    ✓ .swarm.connect

  .update (currently disabled, wait for IPFS 0.4.0)
    - .update.apply
    - .update.check
    - .update.log

  .version
      - running against version 0.3.9
    ✓ checks the version


  44 passing (3s)
  4 pending

[13:57:36] Finished 'mocha' after 3.69 s
[13:57:36] Starting 'daemons:stop'...
[13:57:36] Finished 'daemons:stop' after 33 ms
[13:57:36] Finished 'test:node' after 8.11 s
[13:57:36] Starting 'test:browser'...
[13:57:36] Starting 'daemons:start'...
  ipfs init done - (bootstrap and mdns off) - a
  ipfs init done - (bootstrap and mdns off) - c
  ipfs init done - (bootstrap and mdns off) - b
[13:57:39] Finished 'daemons:start' after 3.74 s
[13:57:39] Starting 'karma'...
22 11 2015 13:57:50.551:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
22 11 2015 13:57:50.558:INFO [launcher]: Starting browser Chrome
22 11 2015 13:57:52.926:INFO [Chrome 46.0.2490 (Mac OS X 10.11.1)]: Connected on socket 6gyGHxTZhCons5YLAAAA with id 51719261

Start:
  nodes
    ✔ connect Node a to b and c
  .add
    ✔ add file
    ✔ add buffer
    ✔ add BIG buffer
    ✔ add path
    ✔ add a nested dir
    ✔ add stream
    ✔ add url
  .block
    ✔ block.put
    ✔ block.get
  .cat
    ✔ cat
    ✔ cat BIG file
  .commands
    ✔ lists commands
  .config
    ✔ .config.{set, get}
    ✔ .config.show
    ✔ .config.replace
  .dht
    ✔ returns an error when getting a non-existent key from the DHT
    ✔ puts and gets a key value pair in the DHT
    ✔ .dht.findprovs
  .diag
    ✔ .diag.net
    ✔ .diag.sys
  .id
    ✔ id
  API
    ✔ has the api object
  .log
    ✔ .log.tail
  .name
    ✔ .name.publish
    ✔ .name.resolve
  .object
    ✔ object.put
    ✔ object.get
    ✔ object.data
    ✔ object.stat
    ✔ object.links
    ✔ object.patch
  .pin
    ✔ .pin.add
    ✔ .pin.list
    ✔ .pin.remove
  .ping
    ✔ ping another peer
  .refs
    ✔ refs
  .send
    ✖ used by every command (skipped)
  .swarm
    ✔ .swarm.peers
    ✔ .swarm.connect
  .update (currently disabled, wait for IPFS 0.4.0)
    ✖ .update.apply (skipped)
    ✖ .update.check (skipped)
    ✖ .update.log (skipped)
LOG: '      - running against version', '0.3.9'
  .version
    ✔ checks the version
  ipfsAPI constructor tests
    parameter permuations
      ✔ opts
      ✔ mutliaddr, opts
      ✔ host, port
      ✔ host, port, opts

Finished in 16.969 secs / 16.875 secs

SUMMARY:
✔ 44 tests completed
ℹ 4 tests skipped
[13:58:10] Finished 'karma' after 31 s
[13:58:10] Starting 'daemons:stop'...
[13:58:10] Finished 'daemons:stop' after 33 ms
[13:58:10] Finished 'test:browser' after 35 s
[13:58:10] Finished 'test' after 43 s
[13:58:10] Finished 'default' after 46 s
```

**Comment by diasdavid** [comment]
What about the remaining failures on travis https://travis-ci.org/ipfs/js-ipfs-api/builds/92548504 ? They are not related with logs calls

**Comment by diasdavid** [comment]
@Dignifiedquire would I be able to persuade you to create branches on ipfs/js-ipfs-api instead of on your fork? It would make collaborating on the same branch way more nicer and avoiding to PR the PR (https://github.com/Dignifiedquire/js-ipfs-api/pull/1) :)

**Pull request closed without merging**
