### PR TITLE
Allow options with ipfs.add

### PR DESCRIPTION
**Pull request by bhstahl**
Hey folks,

Great project! Thought I would update `ipfs.add` and `ipfs.files.add` to accept options, following the [function signature in your docs](https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#javascript---ipfsfilesadddata-options-callback):

`ipfs.files.add(data, [options], [callback])`

and the cli:

```sh
ipfs add [--recursive | -r] [--quiet | -q] [--quieter | -Q] [--silent] [--progress | -p] [--trickle | -t] [--only-hash | -n] [--wrap-with-directory | -w] [--hidden | -H] [--chunker=<chunker> | -s] [--pin=false] [--raw-leaves] [--nocopy] [--fscache] [--cid-version=<cid-version>] [--] <path>...
```

### CODE REVIEW

**Comment by bhstahl** [comment]
It looks like the failed travis tests in this [PR branch build](https://travis-ci.org/ipfs/js-ipfs-api/jobs/242787840) are similar to the failed tests of the most recent master build, such as [#2125.2](https://travis-ci.org/ipfs/js-ipfs-api/jobs/239352702). The tests, including my added ones, passed locally.

**Comment by diasdavid** [comment]
Hi @bhstahl! Thanks for checking js-ipfs-api out and contributing to it.

We reserve the `ipfs.files.add` / `ipfs.add` to follow the API defined in `interface-ipfs-core`. For all the options that interact with the disk directly, we have this util https://github.com/ipfs/js-ipfs-api#utility-functions and it supports most of the options you described there.

**Comment by bhstahl** [comment]
Thanks for taking a look at this @diasdavid! 

Of course, however I _think_ I was following the API defined in `interface-ipfs-core`? Is the function signature defined [here](https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#javascript---ipfsfilesadddata-options-callback) no longer valid? 

>JavaScript - ipfs.files.add(data, [options], [callback])
> **options** is an optional object argument containing the DAG importer options.

**Comment by diasdavid** [comment]
@bhstahl thanks for this PR. I've resolved the merge conflicts and opened a new PR with your changes here https://github.com/ipfs/js-ipfs-api/pull/594 (because Github perms were not letting me resolving the changes in your fork)

**Comment by bhstahl** [comment]
Ah cool, thanks @diasdavid!

**Pull request merged**
