### PR TITLE
Updating CI files

### PR DESCRIPTION
**Pull request by VictorBjelkholm**
This commit updates all CI scripts to the latest version

Creating new PR as the old one was closed without being merged for some reason.

Ref: https://github.com/ipfs/js-ipfs-api/pull/644

### CODE REVIEW

**Comment by diasdavid** [comment]
> Creating new PR as the old one was closed without being merged for some reason.

It was the wording used in https://github.com/ipfs/js-ipfs-api/pull/646. Sorry about that. 

image

**Comment by diasdavid** [comment]
@richardschneider the only tests failing here are Windows ones (check Jenkins), mind taking a look?

**Comment by richardschneider** [comment]
@diasdavid Will look into the 4 failures.

Failure 3 looks like it caused by the previous 2 PubSub failures.  Will investigate.

I've looked at Failure 4 `deal with HTTP weirdness` and do not have a clue.  Could it be a race condition?

**Comment by diasdavid** [comment]
rebased master onto this branch after the fix for test 4 that was done by @richardschneider

**Comment by diasdavid** [comment]
[go-ipfs PubSub is having a weird behaviour on Windows](https://github.com/ipfs/interface-ipfs-core/pull/188#issuecomment-354673246)

**Comment by diasdavid** [comment]
Merging this one, the remaining issue is with go-ipfs and not with CI scripts. Thanks @VictorBjelkholm :)

**Pull request merged**
