### PR TITLE
Fix #140: ipfs add url wrap doesn't work

### LINKED ISSUE #140: ipfs add url wrap doesn't work
Expected:

``` js
ipfs.add(url, {wrap: true}, cb)
```

 would be equivalent to cli's `ipfs add -w`, preserving the last pathname.

### PR DESCRIPTION
**Pull request by hacdias**
`ipfs.util.addFromURL` now works well with the `wrapWithDirectory` option.

### CODE REVIEW

**Comment by hacdias** [comment]
@vmx done! Yeah, I just didn't care much because I'd squash everything before merging and give a good description. But it's fixed now anyway.

**Comment by vmx** [comment]
In regards to the commit message: I normally put the "good" commit message on the first commit, even if things get squashed. This way also the commit message can be reviewed.

**Comment by hacdias** [comment]
@vmx it was probably timing out because I forgot the `done()` in the end. Let's see what happens now.

**Comment by hacdias** [comment]
Thanks @vmx. Ping @diasdavid

**Pull request merged**
