### PR TITLE
Add key api from go-ipfs

### PR DESCRIPTION
**Pull request by MichaelMure**
Hi,

I needed that for my project so maybe it's useful for you as well :)

### CODE REVIEW

**Comment by MichaelMure** [comment]
Fixed the dangling comma. I don't think I'm to blame for the remaining test fail.

**Comment by MichaelMure** [comment]
@diasdavid Is it planned to support the key api here ? I'd like to avoid using a fork.

If yes I can make a better PR.

**Comment by dignifiedquire** [comment]
Thank you @MichaelMure. The goal is to support the whole api that go exposes in this library. It would be great if you could a test for the new method.

**Comment by MichaelMure** [comment]
@dignifiedquire what about interface-ipfs-core ? It needs to be properly spec-ed to go there and the api in go-ipfs and here will be adjusted later ?

**Comment by diasdavid** [comment]
I don't think we will need this to be part of the main interface library, it will be eventually exposed directly through .crypto. Meanwhile this PR looks good, merging it in :)

**Pull request merged**
