### PR TITLE
Auto generate API.md using mocha

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Found a nice way to generate docs from tests, maybe we can combine this with #104

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
cc @VictorBjelkholm @RichardLitt

**Comment by VictorBjelkholm** [comment]
Oh, that does sound awesome! So we can have really clear and focused tests (better for development) that we also can use to generate the API.md? Sounds to good to be true! :)

**Comment by harlantwood** [comment]
so very excellent :+1:

**Comment by RichardLitt** [comment]
This looks pretty awesome! This just grabs it from the tests file?

**Comment by RichardLitt** [comment]
How do I access this file: `test/tmp-disposable-nodes-addrs.json`?

**Comment by Dignifiedquire** [comment]
@RichardLitt not sure what you mean with "access"

**Comment by RichardLitt** [comment]
I mean I don't have that file, and it's in the .gitignore. Am I missing something I ought to be doing to create it?

```  
🐕  gulp mocha
[10:02:35] Using gulpfile ~/src/js-ipfs-api/gulpfile.js
[10:02:35] Starting 'mocha'...
module.js:339
    throw err;
    ^

Error: Cannot find module './tmp-disposable-nodes-addrs.json'
```

**Comment by diasdavid** [comment]
@Dignifiedquire could you make this PR be a PR from a branch on this repo, please? thank you :)

**Comment by Dignifiedquire** [comment]
@diasdavid done

**Pull request closed without merging**
