### PR TITLE
fix: Enforce http protocol for all requests

### LINKED ISSUE #66: Configurable http.request protocol option
Running ipfs-api from an on-disk "file:///.../index.html" does not work. Calling http.request without passing a `protocol` in the opts, it will default to `window.location.protocol`. This causes the following error:
`TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from file://127.0.0.1:5001/api/...`

see `dist/ipfsapi.js:5837`

Could we add a way to explicitly set this protocol option? It could be passed as an opt in the requestAPI or included as a param of IpfsAPI. The latter might be preferable for this scenario so not to require a protocol opt for every method.. maybe it could be IpfsAPI(host_or_multiaddr, port, opts)?

### PR DESCRIPTION
**Pull request by Dignifiedquire**
Closes #66

### CODE REVIEW

**Comment by xicombd** [comment]
:+1:

**Comment by diasdavid** [comment]
Interesting, what happens if it is https? Why do we need to enforce?

**Comment by VictorBjelkholm** [comment]
Hm, this would block anyone from using js-ipfs-api on an https site, which, anyways is not working because the API is only served via http. How can we solve this? Should we solve this?

**Comment by Dignifiedquire** [comment]
We are already enforcing `http` now in nodejs, but for some reason in the browser it's not picking that up from the url. We should make this in option in the long run, but for now this at least brings the browser and node on equal footing

**Comment by diasdavid** [comment]
As discussed on IRC. Let's add this as an option to the creation of ipfsAPI :)

**Comment by jbenet** [comment]
Users should be able to put the exact endpoint directly:

Api('http://localhost:5001/v0/api')
Api('https://user:pass@host/api')
Api('//meh/API')
Api('/ip4/1.2.2.4/tcp/5001/https/v0/api')

(We need to add support to multiaddr for DNS, http paths, and more)

This is why traditional `'host', port` params suck. Info is lost and not
passed through.

**Comment by Dignifiedquire** [comment]
Closing in favor of #67

**Pull request closed without merging**
