### PR TITLE
Migration to next AEgir

### PR DESCRIPTION
**Pull request by diasdavid**
Updated deps and applied the same migrations that happen on the test repo with exception to the PubSub ones https://github.com/ipfs/aegir-test-repo/commit/75c82b3775db69a2e42d1005b767ef78e51161ea##commitcomment-23903275

Seeing a lot of errors coming from JEST, 94 tests fail out of 280.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
js-ipfs-api needs to run in `--no-parallel` mode because of the way test are set up currently.

**Comment by diasdavid** [comment]
Interesting. Ok added that and now I've multiple of one type of error:

```
Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

**Comment by dignifiedquire** [comment]
that means your tests are too slow and you have to increase the timeout for those

**Comment by diasdavid** [comment]
Ok, updated all the timeouts for the tests that had timeouts. Now I've ECONRESET errors.

**Comment by diasdavid** [comment]
Found that these problems also exist with the test repo, see https://github.com/ipfs/aegir-test-repo/pull/1

**Comment by dignifiedquire** [comment]
are you using all patches I made to ipfs-factory on the test repo?

**Comment by diasdavid** [comment]
@dignifiedquire see the PR https://github.com/ipfs/aegir-test-repo/pull/1, it also fails there.

**Comment by diasdavid** [comment]
Seems that in CI most of the test suites are skipped:

image

**Comment by diasdavid** [comment]
nvm, seems that test count is correct, they just not get that pretty print

image

**Comment by dignifiedquire** [comment]
@diasdavid one lonely test failing on circle :D

**Comment by diasdavid** [comment]
@dignifiedquire gotta catch them all

**Comment by dignifiedquire** [comment]
But travis is much slower and still timing out on tons of tests, plus it seems you haven't updated all files yet to pass linting

**Comment by diasdavid** [comment]
- [x] update linting

**Comment by diasdavid** [comment]
@dignifiedquire something is wrong with code coverage (last piece!)

https://travis-ci.org/ipfs/js-ipfs-api/jobs/269735569#L3113-L3166

Running locally I get nothing:

```
> ./node_modules/.bin/aegir codecov

> ./node_modules/.bin/aegir coveralls

```

**Comment by dignifiedquire** [comment]
seems your commands are wrong:

screen shot 2017-08-30 at 12 28 09

**Comment by diasdavid** [comment]
Seems that the default doesn't default

image

**Comment by dignifiedquire** [comment]
@diasdavid I am confused about your statements

- Uploading works fine to both providers as tested here: https://travis-ci.org/ipfs/aegir#L317
- Uploading only happens if you pass the upload flage `-u` or `--upload`
- There is no need to pass a provider if you are not using upload

**Comment by dignifiedquire** [comment]
But I think I see that here is a bug with the aliasing, let me publish a release for that fix, that should solve the issue you are seeing

**Comment by dignifiedquire** [comment]
published 12.0.1 please try that

**Comment by diasdavid** [comment]
Ok, so now tests take over 40 mins to run in Travis plus they fail because it seems that `npm run coverage` interprets timeouts differently - https://travis-ci.org/ipfs/js-ipfs-api/jobs/270369029

**Comment by dignifiedquire** [comment]
@diasdavid well circle ci finally works. And it has much more reasonable build times which could probably be improved with setting up a parallel pipeline. As I mentioned in the community discussion, I think it is time for us to depart ways with travis

**Comment by diasdavid** [comment]
circle is not running Lint nor coverage

running coverage locally also fails and also takes a ton of extra time. I don't think we can blame travis on this one.

**Comment by dignifiedquire** [comment]
Coverage is much slower than regular runs (always has been) because of the overhead of instrumentation. Not sure if there is some regression that jest is a lot slower for this though.

**Comment by dignifiedquire** [comment]
@diasdavid looking at travis output, it seems that the errors are actually not timeouts strange enough: https://travis-ci.org/ipfs/js-ipfs-api/jobs/270369040

**Comment by diasdavid** [comment]
image

It's always Timeout and then a cascade of failures

**Comment by dignifiedquire** [comment]
@diasdavid there is no timeout here: https://travis-ci.org/ipfs/js-ipfs-api/jobs/270685309#L4821

**Comment by dignifiedquire** [comment]
@diasdavid coverage works now on circle, slow travis is still slow

**Comment by diasdavid** [comment]
Thanks @dignifiedquire. I've mixed feelings about accepting our tests getting 2x or more slower due to JEST by just switching coverage to circle..

Just squashed commits and rebased master onto this branch, let's see what's left to do.

**Comment by diasdavid** [comment]
```
Test Node.js
 FAIL  test/interface/swarm.spec.js
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/imp/code/js-ipfs-api/node_modules/interface-ipfs-core/test/fixtures/testfile.txt'

      at Object.fs.openSync (fs.js:652:18)
      at Object.fs.readFileSync (fs.js:553:33)
      at loadFixtures (node_modules/aegir/src/fixtures.js:9:26)
      at Object.<anonymous> (node_modules/interface-ipfs-core/src/pin.js:12:18)
      at Object.<anonymous> (node_modules/interface-ipfs-core/src/index.js:6:15)

 FAIL  test/interface/pubsub.spec.js
  ● Test suite failed to run

    ENOENT: no such file or directory, open '/Users/imp/code/js-ipfs-api/node_modules/interface-ipfs-core/test/fixtures/testfile.txt'

      at Object.fs.openSync (fs.js:652:18)
      at Object.fs.readFileSync (fs.js:553:33)
      at loadFixtures (node_modules/aegir/src/fixtures.js:9:26)
      at Object.<anonymous> (node_modules/interface-ipfs-core/src/pin.js:12:18)
      at Object.<anonymous> (node_modules/interface-ipfs-core/src/index.js:6:15)
```

Needs: https://github.com/ipfs/interface-ipfs-core/pull/154

**Comment by diasdavid** [comment]
Ok, some progress. Now it just crashes because...

image

**Comment by diasdavid** [comment]
Travis go home, you are drunk.

**Comment by dignifiedquire** [comment]
woooooot it is merged :tada:

**Pull request merged**
