### PR TITLE
feat: only-hash option for add/addFromFS/addFromURL

### PR DESCRIPTION
**Pull request by JonKrone**
This adds `only-hash` as a potential querystring arg for files.add, util.addFromFS, and util.addFromURL: `ipfs.add(<content>, { only-hash: true })`.

only-hash allows users to generate a hash for some content without actually adding the content to ipfs.

related issue: https://github.com/ipfs/js-ipfs-api/issues/509

needed for js-ipfs: https://github.com/ipfs/js-ipfs/pull/1233

### CODE REVIEW

**Comment by lgierth** [comment]
Does this also support `-n`?

```
  -n,          --only-hash           bool   - Only chunk and hash - do not write to disk.
```

**Comment by JonKrone** [comment]
> Does this also support -n?

I was thinking that alias support like that is only available through a CLI, (js-ipfs [here](https://github.com/ipfs/js-ipfs/pull/1233/files#diff-606d3a23b2aff2a65d1e977760345e05R143)). Should this API also support aliases? Please explain if I'm missing something, but would you expect `ipfs.add(<content>, { n: true })` to be valid?

**Comment by lgierth** [comment]
Ah I'm sorry, I didn't notice we're in js-ipfs-api

**Comment by JonKrone** [comment]
Haha, no worries 😉. Thanks for the look-over, though.

**Comment by JonKrone** [comment]
CI question: Does anyone know why ESLint finds errors but doesn't report them [here](https://travis-ci.org/ipfs/js-ipfs-api/jobs/345360314#L2822)? This has tricked me a few times, I think.

**Comment by lgierth** [comment]
> Should this API also support aliases?

Actually: maybe. go-ipfs supports option aliases on the API, e.g. `/api/v0/refs?r=true&arg=QmFoo` (because that's where most of the CLI options eventually end up). @diasdavid's call.

**Comment by lgierth** [comment]
But again this is just options objects passed to an API function yeah? Then probably not.

**Comment by JonKrone** [comment]
> Actually: maybe. go-ipfs supports option aliases on the API

Cool, I think js-ipfs could change that as a mild `chore` across the route handlers later on. Do you know why go decided to? Aliases make sense for a CLI because you get lots of human interaction so shortcuts are handy, but most code through an API is generated so aliases don't have that big of an impact.

**Comment by JonKrone** [comment]
CI is failing on object.patch tests: https://travis-ci.org/ipfs/js-ipfs-api/jobs/345383716#L3541

These tests do not fail locally but are also failing on VMX's most recent PR: https://github.com/ipfs/js-ipfs-api/pull/701.

**Comment by diasdavid** [comment]
Alias are supported for some methods (early days) but we decided to bet on the full options names for docs. (Aliases mean + docs and + dup tests)

**Comment by diasdavid** [comment]
@vmx could https://github.com/ipld/js-ipld-dag-pb/releases/tag/v0.13.1 be breaking the tests? HAven't looked too much into it.

**Comment by vmx** [comment]
@diasdavid: Nope, I've just publish js-ipld-dag-pb 0.13.1 just 30mins ago.

**Comment by JonKrone** [comment]
Current status: ready for review / merge.

CI failure is [`pubsub multiple nodes connected: empty() list when no topics are subscribed`](https://travis-ci.org/ipfs/js-ipfs-api/jobs/346327672#L3336).

The `object.patch` CI tests that were failing for vmx and me are passing now for both PRs.

**Comment by diasdavid** [comment]
@JonKrone any reason why to use a different github account for your commits?

See how things are commited by @jkrone rather than @JonKrone 
image

**Comment by JonKrone** [comment]
@diasdavid No reason. It is not a different Github account, just a local `git config user.name` setting that was set to jkrone. I've synced the names and pushed a commit that reflects it.

**Comment by diasdavid** [comment]
let's get https://github.com/ipfs/js-ipfs-api/pull/705 by @vmx in first to that we can see CI green in every PR :)

**Comment by diasdavid** [comment]
@JonKrone please rebase master onto this branch when you have a chance.

**Comment by diasdavid** [comment]
@JonKrone merging this branch into a branch of the repo itself so that we can collaborate 
image

**Pull request merged**
