### PR TITLE
Async Crypto Endeavour

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Comment by diasdavid** [comment]
Seeing these errors:

```
  1) "before all" hook:
     Error: Uncaught TypeError: Cannot read property 'x-stream-output' of undefined (webpack:///src/request-api.js?0369*****************:30:0 <- test/browser.js:49882)



  2) "after all" hook:
     Error: Uncaught TypeError: Cannot read property 'x-stream-output' of undefined (webpack:///src/request-api.js?0369*****************:30:0 <- test/browser.js:49882)

```

**Comment by diasdavid** [comment]
So far looks good to me

**Comment by dignifiedquire** [comment]
CI is being super weird...

**Comment by diasdavid** [comment]
Ok, CI is good now, just fails for the test of adding nested dirs on the browser (reported bug: https://github.com/ipfs/js-ipfs-api/issues/339). 

We've already talked about how to act with regards to this in the past and the decision is to continue moving forward (merge and release), while keep tackling that specific test. To make sure there is no confusion, I'm going to add a note to that in the readme.

**Pull request merged**
