### PR TITLE
circle config

### PR DESCRIPTION
**Pull request by harlantwood**
Use latest stable node version on Circle CI.  Fixes the build.

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
Can we lock this to a specific version instead? I know CircleCI uses 0.10.22 but I'm not sure what stable would be for them. Should be version 5 but CircleCI only comes with version 4 and below pre-installed.

**Comment by harlantwood** [comment]
they use nvm; version 5 at the moment.  what would you like to lock it to?  4.0?  4.1?  5?

**Comment by VictorBjelkholm** [comment]
Ah, did not know that. No, I think we can lock it to version 5. @diasdavid @Dignifiedquire opinions?

**Comment by harlantwood** [comment]
I submitted #108 for travis to test multiple node versions (not so pretty to do that under Circle).  For Circle, I'd suggest we leave it with `stable`, so we're always testing the latest.  Happy to do whatever the more active developers among us prefer though...

**Comment by Dignifiedquire** [comment]
:+1:

**Comment by Dignifiedquire** [comment]
@diasdavid Why are we using circle ci in the first place if it is testing less than travis?

**Comment by harlantwood** [comment]
We set up both circle and Travis to see which we preferred. I originally preferred circle, but now prefer Travis, precisely for its elegance in testing under multiple node versions. I am fine with removing circle, but someone suggested yesterday in an infrastructure issue that it may be useful to test under both, with the idea that sometimes a build fails under one but not the other. I would prefer that we standardize on just one CI system, or at least one per language.

**Comment by harlantwood** [comment]
cc @diasdavid re: https://github.com/ipfs/community/issues/45#issuecomment-154477825

**Comment by diasdavid** [comment]
Should we change that decision? I don't necessarily see any harm of leaving as it is.

**Comment by harlantwood** [comment]
https://github.com/ipfs/community/issues/45#issuecomment-154768152

**Pull request merged**
