### PR TITLE
Fix cat stream bug

### PR DESCRIPTION
**Pull request by ColeMorton**
@dignifiedquire Using your snippet from: ipfs/js-ipfs-api#55.

```
ipfs.cat('some hash', function (err, stream) {
  var res = ''

  stream.on('data', function (chunk) {
    res += chunk.toString()
  })

  stream.on('error', function (err) {
    console.error('Oh nooo', err)    
  })

  stream.on('end', function () {
    console.log('Got:', res)
  })
})
```

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Thank you, sorry for the delayed answer. Could you please make sure that linting passes on the code, other than that it looks good :)

**Comment by diasdavid** [comment]
This will also require a rebase from master onto this branch.

**Comment by diasdavid** [comment]
@ColeMorton ping :) Can you get linting to pass and master rebased onto this branch for the merge? thank you

**Comment by diasdavid** [comment]
ping @ColeMorton :)

**Comment by dignifiedquire** [comment]
This is now fixed in `master`. Please checkout the example and let us know if it works for you know.

**Comment by diasdavid** [comment]
The example sit on https://github.com/ipfs/js-ipfs-api/tree/master/examples :)

**Pull request closed without merging**
