### PR TITLE
request-api allow the http method to be specified

### PR DESCRIPTION
**Pull request by kumavis**
via `options.method = 'GET'`

### CODE REVIEW

**Comment by kumavis** [comment]
not sure if test failure is related...
```
  1 failing
  1) .files callback API .add .createAddStream stream of valid files and dirs:
     Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by diasdavid** [comment]
What was the issue you were having? CORS related?

**Comment by kumavis** [comment]
@diasdavid Parity only supports GET for `block/get` per the apiary API spec
https://github.com/ipfs/http-api-spec/blob/master/apiary.apib#L807

**Comment by diasdavid** [comment]
ah, I see. Well, would it be fine for parity to support just method * for now on that one? I feel that it is easier to make it mimic what go-ipfs does than having to remember everyone to set the method for this specific call.

**Comment by kumavis** [comment]
can we either:
1) change the spec or
2) adhere to the spec

**Comment by kumavis** [comment]
> I feel that it is easier to make it mimic what go-ipfs does

go-ipfs and js-ipfs both handle this method when made as a GET request

**Comment by kumavis** [comment]
https://github.com/ipfs/http-api-spec/issues/124

**Comment by kumavis** [comment]
since parity only implements the single route (block/get) I'll just hit that manually and drop `js-ipfs-api` in the datastore adapter

**Comment by diasdavid** [comment]
on https://github.com/ipfs/js-ipfs-api/pull/551#issuecomment-300046811

We've a lot to do in that land - https://github.com/ipfs/http-api-spec/issues/116

**Pull request closed without merging**
