### PR TITLE
Add current work in progress of readme.md and api.md

### PR DESCRIPTION
**Pull request by VictorBjelkholm**
**Closed in favor of https://github.com/ipfs/js-ipfs-api/pull/104 that has the branch upstream**

This is my current WIP of having a better readme and also added the API docs.

Missing currently:
- [ ] Examples of all the calls
- [ ] Better description of how to use the methods
- [ ] Probably update the TOC
- [ ] Check links et al
- [ ] Proofread

At first, tried to automatically generate the documentation with a script combining the output of `go-ipfs` and reading the method fingerprint from `js-ipfs-api` but got a bit stuck and think I tried to overengineer a solution for something that would be simpler to fix manually.

Related to #58
Ping @RichardLitt

### CODE REVIEW

**Comment by diasdavid** [comment]
It would be sweet to list also the options for each call :)

**Comment by RichardLitt** [comment]
Hmm. Is there any way I can edit this? I can't commit on top of your fork's branch. Could you add this as a branch on ipfs's remote?

**Comment by diasdavid** [comment]
@VictorBjelkholm you have write access to js-ipfs-api repo, you can create a branch on the main repo directly so that everyone can collab :), makes it easier and faster.

**Comment by VictorBjelkholm** [comment]
@RichardLitt @diasdavid sorry about that, have made a new PR with a branch that is here in upstream. https://github.com/ipfs/js-ipfs-api/pull/104

**Comment by jbenet** [comment]
as you go, consider contributing to 
- https://github.com/ipfs/specs/ in general (we need a proper api spec)
- the api overview landing in https://github.com/ipfs/specs/pull/38

**Pull request closed without merging**
