### PR TITLE
docs(examples): move to webpack

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Comment by nycoliver** [comment]
Compiles fine, but ipfs.add throws a TypeError: stream.pipe is not a function
Also in Safari a SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

**Comment by nycoliver** [comment]
For some reason the response from add has two objects, the first of which has no name and no hash: 
https://github.com/ipfs/js-ipfs-api/blob/master/src/add-to-dagnode-transform.js#L23

I think that's causing the `TypeError: stream.pipe is not a function`

Not sure where the `ipfs add error Error: Payload stream closed prematurely` is coming from though.

**Comment by nycoliver** [comment]
Ok, seems the stream.pipe error was due to https://github.com/ipfs/js-ipfs-api/issues/323, not seeing it anymore running the latest go-ipfs master. Not sure where the payload stream error is coming from.

**Comment by diasdavid** [comment]
Seems like it is a bug in go-ipfs. The file gets added through the example, but `ipfs object data` fails, even through go-ipfs cli:

```

» ipfs object data QmSpDiGm6cwbEo1WZyo1YmKH51SboG5brSLqDop4EfAh3o
# returns nothing
» ipfs cat QmSpDiGm6cwbEo1WZyo1YmKH51SboG5brSLqDop4EfAh3o
   sdfadsfas%                                                
» ipfs object get QmSpDiGm6cwbEo1WZyo1YmKH51SboG5brSLqDop4EfAh3o
{"Links":[],"Data":"\u0008\u0002\u0012\r    sdfadsfas\u0018\r"}
```

**Comment by Kubuxu** [comment]
Seems to work here on the master:
```
 ~  ipfs add
ipfs: Reading from /dev/stdin; send Ctrl-d to stop.

Hello world! It is great day, isn't it?
ipfs: Reading from /dev/stdin; send Ctrl-d to stop.

added QmRYcKkokPSnBzwPPVcsRxhj6gGwdhGCUV2mfRRbef4X2V QmRYcKkokPSnBzwPPVcsRxhj6gGwdhGCUV2mfRRbef4X2V
 ~  ipfs cat QmRYcKkokPSnBzwPPVcsRxhj6gGwdhGCUV2mfRRbef4X2V
Hello world! It is great day, isn't it?
 ~  ipfs object data QmRYcKkokPSnBzwPPVcsRxhj6gGwdhGCUV2mfRRbef4X2V
(Hello world! It is great day, isn't it?
(%                                                                                                 ~  ipfs object get QmRYcKkokPSnBzwPPVcsRxhj6gGwdhGCUV2mfRRbef4X2V
{"Links":[],"Data":"\u0008\u0002\u0012(Hello world! It is great day, isn't it?\n\u0018("}
```

**Comment by diasdavid** [comment]
@Kubuxu it is just the files that are added through js-ipfs-api, on that specific example, that make `ipfs object data` fail. 

Note that our tests have coverage for this and they pass, it is just this example. Which makes me think, could the example be just broken? As in, could the webpack compile step be messing with it?

**Comment by nycoliver** [comment]
Yes, it appears to be a problem with the webpack compile step... the example works by importing dist/index.js and https://wzrd.in/standalone/buffer in a script tag. However I would love to be able to just `import IpfsApi from 'ipfs-api'` in my webpack code, especially without running a brfs transform.

**Comment by diasdavid** [comment]
@nycoliver thank you for checking meanwhile! We got slammed yesterday with the IPFS hangouts (you are invited to join btw! https://github.com/ipfs/pm).

I do like the idea of having a pristine js-ipfs-api, just like js-ipfs, which is not poluted by assumptions of 'it can access fs', however, we are not able to pursue that change right now as many people depend on it. We might phase it out to an external module, once https://github.com/ipfs/js-ipfs-api/pull/305 is complete and stable :)

**Comment by nycoliver** [comment]
305 looks great, and thanks for the invitation!

I'll use ipfs-api in a script tag for now but such a hacky solution is really uncomfortable. Hoping this issue gets solved and I can bundle with webpack soon.

**Comment by nginnever** [comment]
Also ran into this webpacking a new project using js-ipfs-api. I was able to reproduce from calling the ``id`` command however...

``ipfs.id()`` both in promise and callback.

 returns

``Error: Payload stream closed prematurely``

**Comment by dignifiedquire** [comment]
Will wait until #390 is merged, as that makes building and things a lot simpler

**Comment by dignifiedquire** [comment]
Fixed in #414

**Pull request closed without merging**
