### PR TITLE
refactor: Use aegir

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Updated version of #233

**Comment by diasdavid** [comment]
Seems that there are some leftovers

```
/home/travis/build/ipfs/js-ipfs-api/node_modules/aegir/config/webpack.js:15
if (pkg.aegir && pkg.dignified.webpack) {
                              ^
TypeError: Cannot read property 'webpack' of undefined
```

**Comment by dignifiedquire** [comment]
@diasdavid that's already fixed, the main issue is this: https://travis-ci.org/ipfs/js-ipfs-api/jobs/122904881 which I'm not sure how to solve

**Comment by diasdavid** [comment]
We need to find a way to skip the `log` tests in PhantomJS, they are the only ones that break the process.

**Comment by dignifiedquire** [comment]
@diasdavid this should turn green any moment now, skipping `log.tail` on PhantomJS for now

**Comment by diasdavid** [comment]
sweet! thank you :) Need to release then.

**Pull request merged**
