### PR TITLE
chore: test against latest go-ipfs

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by diasdavid** [comment]
Seems that new go-ipfs is slower:

https://travis-ci.org/ipfs/js-ipfs-api/jobs/271122984#L5294-L5325

```
 1) .name "before all" hook:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  
  2) .pin "before all" hook:
     Uncaught AssertionError: expected [Error: connect ECONNREFUSED 127.0.0.1:36291] to not exist
      at ipfs.id (test/name.spec.js:42:30)
      at send (src/id.js:9:844)
      at f (node_modules/once/once.js:25:25)
      at ClientRequest.req.on.err (src/utils/request-api.js:9:8573)
      at Socket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
  3) .dht "before all" hook:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  
  4) .pubsub promise API "before all" hook:
     Uncaught TypeError: Cannot read property 'currentRetry' of undefined
      at node_modules/async/internal/parallel.js:39:9
      at node_modules/async/internal/once.js:12:16
      at iterateeCallback (node_modules/async/internal/eachOfLimit.js:44:17)
      at node_modules/async/internal/onlyOnce.js:12:16
      at node_modules/async/internal/parallel.js:36:13
      at f (node_modules/once/once.js:25:25)
      at ClientRequest.req.on.err (src/utils/request-api.js:9:8573)
      at Socket.socketErrorListener (_http_client.js:401:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by diasdavid** [comment]
It seems that things got slower and therefore tests started timing out and doing funky things. Bumping the timeouts made them pass.

**Comment by diasdavid** [comment]
Ok, other tests solved, now PubSub fails like this:

```
 1) .pubsub promise API .ls:
      AssertionError: expected [ 'pubsub-tests-0.1301018467081798' ] to deeply equal []
      + expected - actual
      -[
      -  "pubsub-tests-0.1301018467081798"
      -]
      +[]
      
      at ipfs1.pubsub.ls.then (node_modules/interface-ipfs-core/src/pubsub.js:657:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

@Kubuxu did something change with regards to PubSub in go-ipfs? Maybe @vyzo knows too

**Comment by Kubuxu** [comment]
No that I know of.

**Comment by diasdavid** [comment]
I believe this was the root cause: https://github.com/ipfs/interface-ipfs-core/commit/1fcca0305fc9ca42e228f9a64d9bb38d63c1bce2

Let's see :)

**Comment by diasdavid** [comment]
✅ https://travis-ci.org/ipfs/js-ipfs-api/jobs/271228780

**Comment by diasdavid** [comment]
More greeeen ✅ https://travis-ci.org/ipfs/js-ipfs-api/jobs/271228774

**Comment by diasdavid** [comment]
Ok, now it is just a old one that is back:

```
 .files callback API .add .createAddStream stream of valid files and dirs:
     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
https://github.com/ipfs/js-ipfs-api/issues/572

**Pull request merged**
