### PR TITLE
Avoid crash for responses without 'content-type' header

### PR DESCRIPTION
**Pull request by xicombd**
For example, when the response is a 200 OK without body

### CODE REVIEW

**Comment by dignifiedquire** [comment]
can we have a test for this?

**Comment by xicombd** [comment]
AFAIK `go-ipfs` which is used on the tests always replies with `content-type`, I got this problem while working on `js-ipfs`, as such I added a test that uses it's own very basic `http` server. 
Let me know what you think :octocat:

**Comment by diasdavid** [comment]
@xicombd LGTM, but since it is such a odd looking test, could you add 2 lines of code comments explaining why that test exists, otherwise it might get quickly deleted by someone in the future

**Comment by xicombd** [comment]
@diasdavid added the the comments

**Pull request merged**
