### PR TITLE
Issue with how Fixtures get loaded

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by diasdavid** [comment]
Ref from @vmx:
- https://github.com/feross/buffer/pull/178
- https://github.com/feross/buffer/issues/177

**Comment by diasdavid** [comment]
It appears that the real issue is how fixtures get loaded in interface-ipfs-core https://github.com/ipfs/interface-ipfs-core/blob/master/js/src/files.js#L29-L52

aegir makes some hard assumptions on where the fixtures are located https://github.com/ipfs/aegir/blob/master/src/fixtures.js#L18-L22

https://github.com/ipfs/interface-ipfs-core/pull/205 broke that assumption.

**Comment by diasdavid** [comment]
https://github.com/ipfs/aegir/pull/196 & https://github.com/ipfs/interface-ipfs-core/pull/218 solve this.

**Comment by musicsmithnz** [comment]
I found this thread searching for the error "content.once is not a function" which led me to this page. 

I'm getting this error when adding an array of objects to ipfs.files.add. 

`
let ipfsFiles=[]

ipfsFiles.push({
  path: some_path,
  content: some_array_buffer
});

ipfs.files.add(
  ipfsFiles,
  (err, files) => {
    if (err) {
      console.log(err)
    } else {
      console.log(files)
    }
  }
)
`

**Comment by x5engine** [comment]
still no fix in 2019, almost 2020 lol

**Pull request merged**
