### PR TITLE
[WIP] fix: propagate trailer errors correctly

### PR DESCRIPTION
**Pull request by dryajov**
fixes - https://github.com/ipfs/js-ipfs-api/issues/607

needs tests

### CODE REVIEW

**Comment by diasdavid** [comment]
@richardschneider Windows tests seem to be inconsistent (failing again), mind taking a look? It is not due to this PR but since Appveyor was gracious enough to let this PR do a run, we should take advantage and look at what it says.

**Comment by dryajov** [comment]
@daviddias, yep working on tests right now.

**Comment by richardschneider** [comment]
It looks like the `.refs` test is failing because of CRLFs; see https://github.com/ipfs/js-ipfs-repo/pull/153#issuecomment-346320309.

**Comment by richardschneider** [comment]
@diasdavid I'm still getting `.refs` test failure on windows.  Do you want to open a new issue/pr?

**Pull request merged**
