### PR TITLE
feat(breaking change): stream to value on files read

### PR DESCRIPTION
**Pull request by hacdias**
Use `streamToValue` on `files.read` to return a beautiful Buffer instead of a stream.

### CODE REVIEW

**Comment by hacdias** [comment]
The tests seem to be passing (some not related to files.read randomly fail). ping @diasdavid  😄

**Comment by diasdavid** [comment]
@hacdias let's sync up first with all these API changes. We can't simply break the API without understanding why and have a good way to notify users.

Spec first out the Files API and then propose the changes.

**Comment by hacdias** [comment]
Sure, makes sense @diasdavid

**Comment by hacdias** [comment]
@diasdavid the spec is done and merged 😄

**Comment by diasdavid** [comment]
@hacdias can we get CI to pass here?

**Comment by hacdias** [comment]
image

@diasdavid Travis seems to be passing

**Pull request merged**
