### PR TITLE
Get CI Green

### PR DESCRIPTION
**Pull request by diasdavid**
#713

### CODE REVIEW

**Comment by diasdavid** [comment]
@vmx let's see what CI tells us now :)

**Comment by diasdavid** [comment]
Some new test fails, but browser tests do run! :)

image

**Comment by diasdavid** [comment]
@vmx can you land the rest?

**Comment by vmx** [comment]
@diasdavid That one needs https://github.com/ipfs/interface-ipfs-core/pull/227#issuecomment-372696424. Either reverting the commit or fixing the tests.

I currently work on a branch with that one reverted trying to fix the other sporadic failures.

**Comment by vmx** [comment]
One of the recent merges broke the MFS files tests. Reverting https://github.com/ipfs/interface-ipfs-core/pull/227 isn't enough anymore.

**Pull request closed without merging**
