### PR TITLE
Support key/rm and key/rename

### PR DESCRIPTION
**Pull request by richardschneider**
Needed for https://github.com/ipfs/js-ipfs/pull/1133

### CODE REVIEW

**Comment by diasdavid** [comment]
@richardschneider would you be so kind of standardizing the ipfs.key and ipfs.crypt APIs through https://github.com/ipfs/interface-ipfs-core while you are implementing it in both js-ipfs and js-ipfs-api?

**Comment by richardschneider** [comment]
@diasdavid yes this is today's task.

**Comment by diasdavid** [comment]
@richardschneider released interface-ipfs-core with new test, make sure to test with latest deps

**Comment by richardschneider** [comment]
@diasdavid The added tests should be **failing** because `js-ipfs` does not yet support the Key API.  The PR https://github.com/ipfs/js-ipfs/pull/1133 needs to be merged.  The PR relies upon https://github.com/ipfs/js-ipfs-repo/pull/156 and an NPM release of js-libp2p-keychain.

Its the old chicken and egg problem.

**Comment by diasdavid** [comment]
> The added tests should be failing because js-ipfs

@richardschneider this is the **js-ipfs-api** PR, not js-ipfs.

**Comment by richardschneider** [comment]
Yes, I now which repo I'm making changes to.  `js-ipfs-api` runs the tests from `interface-ipfs-core` which use which in-turn need an"ipfs server" (either js-ipfs or go-ipfs).

**Comment by richardschneider** [comment]
@diasdavid any comments?

**Comment by diasdavid** [comment]
@richardschneider can we get CI green?

**Comment by diasdavid** [comment]
@richardschneider one test is failing:

```
  1) .key
       .rm
         removes a key:

      Uncaught AssertionError: expected [] to have a length of 1 but got 0
      + expected - actual

      -0
      +1
      
      at ipfs.key.rm (node_modules/interface-ipfs-core/src/key.js:126:36)
      at f (node_modules/once/once.js:25:25)
      at streamToValue (src/utils/stream-to-json-value.js:4:300)
      at data (src/utils/stream-to-value.js:3:168)
      at ConcatStream.<anonymous> (node_modules/concat-stream/index.js:36:43)
      at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:607:14)
      at afterWrite (node_modules/readable-stream/lib/_stream_writable.js:470:3)
      at _combinedTickCallback (internal/process/next_tick.js:144:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

```

**Comment by richardschneider** [comment]
@diasdavid Once https://github.com/ipfs/interface-ipfs-core/pull/185 is merged.  The above test will work.

**Comment by diasdavid** [comment]
@richardschneider watch out for the wording used in PR's.

The "fix" here:
image

Closed this PR by mistake.

**Comment by richardschneider** [comment]
@diasdavid Please provide the wording you like.

**Comment by diasdavid** [comment]
@richardschneider it doesn't matter if I like it or not, it is just how Github works. You say "fix X" and Github will close it if merged.

**Pull request merged**
